import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../theme/ThemeContext';

export function createJournalStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    heading: {
      fontSize: 20,
      fontWeight: '700',
      color: colors.text,
    },
    newButton: {
      backgroundColor: colors.accent,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
    },
    newButtonText: {
      color: colors.accentText,
      fontWeight: '600',
      fontSize: 14,
    },
    cancel: {
      fontSize: 15,
      color: '#aaa',
      width: 60,
    },
    saveText: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.text,
      width: 60,
      textAlign: 'right',
    },
    empty: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyText: {
      color: '#aaa',
      fontSize: 15,
    },
    list: {
      padding: 16,
      gap: 12,
    },
    card: {
      backgroundColor: colors.surfaceMuted,
      borderRadius: 12,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
    },
    cardContent: {
      flex: 1,
      marginRight: 12,
    },
    cardTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 4,
    },
    cardDate: {
      fontSize: 12,
      color: '#aaa',
      marginBottom: 6,
    },
    cardBody: {
      fontSize: 14,
      color: '#555',
      lineHeight: 20,
    },
    deleteButton: {
      paddingVertical: 4,
      paddingHorizontal: 8,
    },
    deleteText: {
      color: '#e74c3c',
      fontSize: 13,
      fontWeight: '500',
    },
    form: {
      padding: 20,
      flexGrow: 1,
    },
    titleInput: {
      fontSize: 22,
      fontWeight: '600',
      color: '#111',
      paddingVertical: 8,
    },
    divider: {
      height: 1,
      backgroundColor: colors.border,
      marginVertical: 12,
    },
    bodyInput: {
      fontSize: 16,
      color: colors.textMuted,
      lineHeight: 24,
      minHeight: 300,
    },
    backText: {
      fontSize: 15,
      color: colors.text,
      fontWeight: '500',
    },
    viewTitle: {
      fontSize: 26,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 6,
    },
    viewBody: {
      fontSize: 16,
      color: colors.textMuted,
      lineHeight: 26,
    },
    aiButton: {
      backgroundColor: colors.accent,
      marginHorizontal: 20,
      marginBottom: 16,
      marginTop: 8,
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: 'center',
    },
    aiButtonText: {
      color: colors.accentText,
      fontWeight: '600',
      fontSize: 15,
      letterSpacing: 0.3,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.4)',
      justifyContent: 'flex-end',
    },
    modalContainer: {
      backgroundColor: colors.background,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingTop: 20,
      paddingHorizontal: 20,
      paddingBottom: 32,
      maxHeight: '80%',
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 6,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
      flex: 1,
      textAlign: 'center',
    },
    modalBack: {
      fontSize: 14,
      color: '#aaa',
      fontWeight: '500',
      width: 60,
    },
    modalClose: {
      fontSize: 18,
      color: '#aaa',
      fontWeight: '600',
      padding: 4,
      width: 60,
      textAlign: 'right',
    },
    modalSubtitle: {
      fontSize: 13,
      color: '#aaa',
      marginBottom: 16,
      textAlign: 'center',
    },
    modalList: {
      flexGrow: 0,
    },
    typeCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surfaceMuted,
      borderRadius: 12,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 10,
    },
    typeEmoji: {
      fontSize: 28,
      marginRight: 14,
    },
    typeTextContainer: {
      flex: 1,
    },
    typeLabel: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 2,
    },
    typeDescription: {
      fontSize: 12,
      color: '#aaa',
    },
    typeArrow: {
      fontSize: 22,
      color: '#bbb',
      marginLeft: 8,
    },
    modalCard: {
      backgroundColor: colors.surfaceMuted,
      borderRadius: 12,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 10,
    },
    modalCardSelected: {
      borderColor: colors.accent,
      backgroundColor: colors.surfaceMuted,
    },
    modalCardRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
    },
    modalCardCheckbox: {
      width: 22,
      height: 22,
      borderRadius: 6,
      borderWidth: 2,
      borderColor: '#ddd',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 2,
      backgroundColor: colors.background,
    },
    modalCardCheckmark: {
      fontSize: 13,
      color: colors.text,
      fontWeight: '700',
    },
    modalCardTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.text,
      marginBottom: 3,
    },
    modalCardDate: {
      fontSize: 11,
      color: '#aaa',
      marginBottom: 5,
    },
    modalCardBody: {
      fontSize: 13,
      color: '#555',
      lineHeight: 18,
    },
    analyseButton: {
      backgroundColor: colors.accent,
      marginTop: 14,
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: 'center',
    },
    analyseButtonDisabled: {
      backgroundColor: '#e0e0e0',
    },
    analyseButtonText: {
      color: colors.accentText,
      fontWeight: '600',
      fontSize: 15,
    },
    modalLoading: {
      paddingVertical: 48,
      alignItems: 'center',
    },
    modalLoadingText: {
      fontSize: 14,
      color: '#aaa',
      marginTop: 12,
    },
    insightsText: {
      fontSize: 15,
      color: colors.textMuted,
      lineHeight: 24,
    },
    modalBackButton: {
      marginTop: 16,
      paddingVertical: 12,
      alignItems: 'center',
    },
    modalBackButtonText: {
      fontSize: 14,
      color: '#aaa',
      fontWeight: '500',
    },
  });
}